Bloco de Mapa (GPS)
Math-42/ZenView pull request #21
Opened 2021-09-22 00:21 UTC by mairacanal

Adição do bloco de GPS por meio da biblioteca Leaflet. Se possível, revisem o código e testem o mapa com mock data.

Closes #9

2021-09-23 18:29 UTC, Math-42 requested changes

2021-09-23 18:29 UTC, Math-42 commented on src/components/blocks/Blocks/GPS/GPS.js
> +		}).setView([-22, -47.890833], 12);
remover o magic number das coordenadas da USP

2021-09-23 18:29 UTC, Math-42 commented on src/components/blocks/Blocks/GPS/GPS.js
> +	get formConfig() {
Aqui você deve retornar as informações do jeito que quer que o menu as mostre, como vc nunca alterou o _formConfig, toda vez que o bloco é reaberto, as informações enviadas são as antigas.

2021-09-28 03:09 UTC, Grillo-0 approved these changes

2021-09-28 11:38 UTC, merged