Feature/terminal
Math-42/ZenView pull request #22
Opened 2021-09-23 22:45 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [X] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Adicionado o bloco de terminal do sistema, também tirei o antigo terminal do sistema do side menu pra não ficar repetitivo

Closes #13

2021-09-25 21:00 UTC, mairacanal commented
Era realmente para dar merge na master e não na uPlot?

2021-09-26 17:37 UTC, Grillo-0 commented
> Era realmente para dar merge na master e não na uPlot?

Não mesmo kkkk, troquei aqui

2021-10-01 11:51 UTC, mairacanal requested changes

2021-10-01 11:51 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +		super(preConfig,htmlComponent)
Indentação

2021-10-01 11:51 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +		const widget = this.htmlComponent.parentElement;
Indentação

2021-10-01 11:51 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +        this.htmlComponent.appendChild(this.configSystemTerminal());
Não seria melhor dar o appendChild dentro da função `configSystemTerminal` ao invés de retornar o valor?

2021-10-01 11:51 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +		});
Indentação, por que chorás?

2021-10-01 11:51 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +        this.ptyProcess = pty.spawn(os.platform() === 'win32' ? 'powershell.exe' : 'bash', [], {
Poderia, talvez, no menu, dar a possibilidade de escolher o shell do terminal.

2021-10-01 13:56 UTC, Grillo-0 commented on src/components/blocks/Blocks/terminal/terminal.js
> +		});
![image](https://user-images.githubusercontent.com/53825439/135632199-745f162b-45de-43cc-88b8-224801ca9e4a.png)
Que estranho, deve ser algum conflito de eu usar espaços como tabs

2021-10-01 14:21 UTC, Grillo-0 commented on src/components/blocks/Blocks/terminal/terminal.js
> +        this.ptyProcess = pty.spawn(os.platform() === 'win32' ? 'powershell.exe' : 'bash', [], {
Poderia só setar pro terminal default do usuário, por exemplo, eu uso fish, ai o shell do terminal do Zentih Monitor seria o fish.

2021-10-02 00:07 UTC, mairacanal commented on src/components/blocks/Blocks/terminal/terminal.js
> +        this.ptyProcess = pty.spawn(os.platform() === 'win32' ? 'powershell.exe' : 'bash', [], {
Pode ser uma boa

2021-10-02 03:23 UTC, Grillo-0 commented on src/components/blocks/Blocks/terminal/terminal.js
> +		});
Resolvi aqui, era isso mesmo

2021-10-02 10:52 UTC, mairacanal approved these changes

2021-10-02 14:15 UTC, merged