Feature/block header
Math-42/ZenView pull request #23
Opened 2021-10-05 05:39 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [X] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Coloquei os botões de remover e editar dos blocos no header do bloco, e também ajeitei o titulo do bloco que estava apagando os botões quando era colocado
![Screenshot from 2021-10-05 02-38-44](https://user-images.githubusercontent.com/53825439/135966592-e879bf4a-09a2-418d-bcca-08cf5b1f8a1d.png)

2021-10-10 10:43 UTC, mairacanal requested changes
Eu aumentaria o padding da classe `.blockHeader`para `0.5em`. Creio que assim ficaria mais simétrico.

2021-10-10 10:43 UTC, mairacanal commented on src/components/blockContainer/blockContainer.js
>  		};
Eu acho que esse evento pode ser apagado agora, já que não tem mais o efeito de passar o mouse por cima

2021-10-10 10:43 UTC, mairacanal commented on src/css/block.css
> +	/*bottom :13px;*/
Apagar o comentário

2021-10-10 10:43 UTC, mairacanal commented on src/css/block.css
> +	/*bottom :13px;*/
Apagar o comentário

2021-10-11 20:23 UTC, Math-42 requested changes

2021-10-11 20:23 UTC, Math-42 commented on src/css/block.css
>      position: absolute;
Juntar essas duas classes, elas são praticametne a mesma coisa apenas alterando o nome.

2021-10-13 14:45 UTC, mairacanal approved these changes

2021-10-13 20:16 UTC, merged