Edit menu
Math-42/ZenView pull request #24
Opened 2021-10-11 20:20 UTC by Math-42

## What type of PR is this? (check all applicable)
- [x] ✨ Feature
- [x] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:
Refatorando todo o menu de edição de séries e consertando load do plot de um arquivo

OBS: Esses pull request não se refere ao problema de melhoria visual do plot, isso irá vir separadamente, visto que já estava ficando muito grande.

# Testing

2021-10-11 20:26 UTC, mairacanal commented
10 mil linhas... Cool. Cool. Cool, cool, cool.

2021-10-11 20:28 UTC, Math-42 commented
> 10 mil linhas... Cool. Cool. Cool, cool, cool.

é o arquivo de config do package json KKKKKKKKKK

2021-10-11 20:44 UTC, mairacanal requested changes
Nunca mais faça um PR desse tamanho se você tem amor ao próximo

2021-10-11 20:44 UTC, mairacanal commented on src/components/dashBoard/DashBoard.js
> +			newBlock.title = blockLog.title;
Será que o `title` não poderia está no construtor da classe `BlockContainer`?

2021-10-11 20:44 UTC, mairacanal commented on src/components/eventHandler/eventHandler.js
> +		};
Será que tem como reduzir o número de eventos relacionados a abrir o menu?

2021-10-11 20:48 UTC, Math-42 commented on src/components/eventHandler/eventHandler.js
> +		};
Poderia, mas esse menu ai é o dos cads que você fez, ai teria que criar outra lógica para abrir e fechar eles.

2021-10-11 23:37 UTC, mairacanal commented on src/components/eventHandler/eventHandler.js
> +		};
Eu vi todos e, de fato, eles tem contextos diferentes.

2021-10-14 10:52 UTC, mairacanal approved these changes

2021-10-14 10:54 UTC, merged