Corrected the css to work in all block types
Math-42/ZenView pull request #26
Opened 2021-10-14 16:49 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:
o CSS do header só estava funcionando para o bloco do GPS, se poderem testem ai.

2021-10-14 23:43 UTC, mairacanal requested changes

2021-10-14 23:43 UTC, mairacanal commented on src/components/blockContainer/blockContainer.js
> +        this.headerTitle.className = "blockTitle";
Indentação

2021-10-16 19:33 UTC, Grillo-0 commented on src/components/blockContainer/blockContainer.js
> +        this.headerTitle.className = "blockTitle";
O velho problema de eu usar 4 espaços como tab e os arquivos estarem com um tab mesmo

2021-10-16 20:19 UTC, mairacanal approved these changes

2021-10-16 20:19 UTC, merged