Feature/UUID input
Math-42/ZenView pull request #29
Opened 2021-11-08 02:01 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [x] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Rework dos inputs sendo principalmente a adição de um uuid para cada input, para assim facilitar o código envolvendo essa parte

2021-11-08 19:46 UTC, mairacanal requested changes
Eu não consigo criar um dashboard após as modificações. 

### Passo a passo para gerar o erro
Entre no menu "Novo Dashboard" e coloque um nome, um diretório e um número de entradas. Em seguida, clique em "Criar".

Eu obtive o seguinte erro:

```
/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/input.js:13 Uncaught TypeError: Cannot read property 'raw' of undefined
    at new Input (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/input.js:13)
    at InputGroup.generateInputs (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/inputGroup.js:59)
    at InputGroup.newConstructor (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/inputGroup.js:29)
    at new InputGroup (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/inputGroup.js:19)
    at DashBoard.newConstructor (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/dashBoard.js:34)
    at new DashBoard (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/classes/dashBoard.js:21)
    at DashBoardsManager.newDashBoard (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/dashBoard/DashBoardsManager.js:155)
    at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/dashBoard/DashBoardsManager.js:300
    at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:245
    at EventHandler.dispatchEvent (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:255)
```

Como eu obtive esse erro, eu não consegui ir muito além disso para realizar os testes.

2021-11-08 22:48 UTC, mairacanal requested changes
Esse PR acabou quebrando o Mapa. Como o bloco do Mapa é pequeno, nesse PR mesmo, você pode realizar essas modificações. Além disso, tem um problema que quando você muda o nome de um input, que está selecionado em algum bloco, essa seleção é perdida e o bloco vai selecionar a column_0 após a mudança de nome.

2021-11-17 14:56 UTC, mairacanal requested changes

2021-11-17 14:56 UTC, mairacanal commented on src/components/inputHandler/inputHandler.js
> +		console.log(this.scope);
Apagar essa mensagem de debug

2021-11-17 14:56 UTC, mairacanal commented on src/classes/input.js
> +			redable: expression.redable,
Typo: redable -> readable

2021-11-17 18:19 UTC, Grillo-0 commented on src/classes/input.js
> +			redable: expression.redable,
Feito 👍🏻

2021-11-17 18:22 UTC, Grillo-0 commented on src/components/inputHandler/inputHandler.js
> +		console.log(this.scope);
Feito 👍🏻

2021-11-17 22:03 UTC, mairacanal requested changes
Eu ainda estou tendo o seguinte erro quando eu coloco para plotar no mapa (apesar dos pontos serem plotados no mapa)

```
Uncaught Error: Invalid LatLng object: (undefined, undefined)
    at new LatLng (LatLng.js:32)
    at coordsToLatLng (GeoJSON.js:235)
    at geometryToLayer (GeoJSON.js:186)
    at NewClass.addData (GeoJSON.js:117)
    at GPS.updateData (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blocks/Blocks/GPS/GPS.js:92)
    at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blockContainer/blockContainer.js:256
    at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:251
    at EventHandler.dispatchEvent (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:261)
    at EventHandler.DataIsProcessed (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:73)
    at InputHandler.solve (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/inputHandler/inputHandler.js:329)
```

2021-11-17 23:29 UTC, Grillo-0 commented
> Eu ainda estou tendo o seguinte erro quando eu coloco para plotar no mapa (apesar dos pontos serem plotados no mapa).
> 
> ### Como obter esse erro?
> Colocar um CSV para ser plotado no mapa.
> 
> ```
> Uncaught Error: Invalid LatLng object: (undefined, undefined)
>     at new LatLng (LatLng.js:32)
>     at coordsToLatLng (GeoJSON.js:235)
>     at geometryToLayer (GeoJSON.js:186)
>     at NewClass.addData (GeoJSON.js:117)
>     at GPS.updateData (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blocks/Blocks/GPS/GPS.js:92)
>     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blockContainer/blockContainer.js:256
>     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:251
>     at EventHandler.dispatchEvent (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:261)
>     at EventHandler.DataIsProcessed (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:73)
>     at InputHandler.solve (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/inputHandler/inputHandler.js:329)
> ```

Que estranho, aqui ele ta funcionando. Como eu dei push -f talvez tenha bugado a branch ai pra vc (como ja aconteceu uma outra vez), to vendo que esse comando não é tão bom de ser usado

2021-11-18 11:19 UTC, mairacanal commented
> > Eu ainda estou tendo o seguinte erro quando eu coloco para plotar no mapa (apesar dos pontos serem plotados no mapa).
> > ### Como obter esse erro?
> > Colocar um CSV para ser plotado no mapa.
> > ```
> > Uncaught Error: Invalid LatLng object: (undefined, undefined)
> >     at new LatLng (LatLng.js:32)
> >     at coordsToLatLng (GeoJSON.js:235)
> >     at geometryToLayer (GeoJSON.js:186)
> >     at NewClass.addData (GeoJSON.js:117)
> >     at GPS.updateData (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blocks/Blocks/GPS/GPS.js:92)
> >     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blockContainer/blockContainer.js:256
> >     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:251
> >     at EventHandler.dispatchEvent (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:261)
> >     at EventHandler.DataIsProcessed (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:73)
> >     at InputHandler.solve (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/inputHandler/inputHandler.js:329)
> > ```
> 
> Que estranho, aqui ele ta funcionando. Como eu dei push -f talvez tenha bugado a branch ai pra vc (como ja aconteceu uma outra vez), to vendo que esse comando não é tão bom de ser usado

Então, eu apaguei a branch, dei `git fetch` e pushei a branch do remoto. Mas vou tentar novamente.

2021-11-18 11:23 UTC, mairacanal commented
> > > Eu ainda estou tendo o seguinte erro quando eu coloco para plotar no mapa (apesar dos pontos serem plotados no mapa).
> > > ### Como obter esse erro?
> > > Colocar um CSV para ser plotado no mapa.
> > > ```
> > > Uncaught Error: Invalid LatLng object: (undefined, undefined)
> > >     at new LatLng (LatLng.js:32)
> > >     at coordsToLatLng (GeoJSON.js:235)
> > >     at geometryToLayer (GeoJSON.js:186)
> > >     at NewClass.addData (GeoJSON.js:117)
> > >     at GPS.updateData (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blocks/Blocks/GPS/GPS.js:92)
> > >     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/blockContainer/blockContainer.js:256
> > >     at /home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:251
> > >     at EventHandler.dispatchEvent (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:261)
> > >     at EventHandler.DataIsProcessed (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/eventHandler/eventHandler.js:73)
> > >     at InputHandler.solve (/home/mairacanal/Dropbox/USP/ZENITH/Repositórios/ZenView/src/components/inputHandler/inputHandler.js:329)
> > > ```
> > 
> > 
> > Que estranho, aqui ele ta funcionando. Como eu dei push -f talvez tenha bugado a branch ai pra vc (como ja aconteceu uma outra vez), to vendo que esse comando não é tão bom de ser usado
> 
> Então, eu apaguei a branch, dei `git fetch` e pushei a branch do remoto. Mas vou tentar novamente.

Eu acho que eu coloquei o CSV sujo ao invés do CSV normal. Desculpa pela confusão. Vou aprovar o PR.

2021-11-18 11:23 UTC, mairacanal approved these changes

2021-11-18 12:10 UTC, merged