Tratamento de Erros
Math-42/ZenView pull request #30
Opened 2021-11-08 21:24 UTC by mairacanal

# Mudanças:
- Adiciona a biblioteca Notus e notificações personalizadas
- Adiciona uma classe para gerenciar notificações e um evento para mandá-las
- Descarta linhas que possuem informações inválidas

# Como testar?
- Usar um CSV sem NaN
- Usar um CSV com NaN esporádicas

2021-11-08 22:18 UTC, Math-42 requested changes
O código em si ficou ótimo, apenas duas observaçoes:

Está usando o eslint? se não estiver ative ele e passe em todos os arquivos que alterou.
Outro detalhe é que o notifier ficou dentro da pasta classes, nessa pasta ficam apenas as classes que funcionam como structs, apenas dados, acredito que ele deveria ficar dentro da pasta components.

2021-11-08 22:21 UTC, Grillo-0 requested changes

2021-11-08 22:21 UTC, Grillo-0 commented on src/classes/notifier.js
> +module.exports = class Notifer {
```suggestion
module.exports = class Notifier {
```

2021-11-08 22:21 UTC, Grillo-0 commented on src/mainwindow.js
> +		this.Notifer = new Notifer();
```suggestion
		this.Notifier = new Notifier();
```

2021-11-08 22:21 UTC, Grillo-0 commented on src/mainwindow.js
> +const Notifer = require('./classes/notifier');
```suggestion
const Notifier = require('./classes/notifier');
```

2021-11-09 00:28 UTC, mairacanal commented
> O código em si ficou ótimo, apenas duas observaçoes:
> 
> Está usando o eslint? se não estiver ative ele e passe em todos os arquivos que alterou. Outro detalhe é que o notifier ficou dentro da pasta classes, nessa pasta ficam apenas as classes que funcionam como structs, apenas dados, acredito que ele deveria ficar dentro da pasta components.

Tem alguma pasta em específico que você sugere?

2021-11-09 00:55 UTC, Math-42 commented
> > O código em si ficou ótimo, apenas duas observaçoes:
> > Está usando o eslint? se não estiver ative ele e passe em todos os arquivos que alterou. Outro detalhe é que o notifier ficou dentro da pasta classes, nessa pasta ficam apenas as classes que funcionam como structs, apenas dados, acredito que ele deveria ficar dentro da pasta components.
> 
> @Math-42 Tem alguma pasta em específico que você sugere?

Dentro da pasta src/components

2021-11-09 12:08 UTC, Grillo-0 approved these changes

2021-11-11 01:57 UTC, Math-42 approved these changes

2021-11-11 20:52 UTC, merged